[versions]
junit = "6.1.0"
assertj-core = "3.27.7"
slf4j-api = "2.0.18"
log4j = "2.26.0"
lombok-plugin = "9.5.0"
sonarqube-plugin = "6.2.0.5505"
mockito-core = "5.23.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }